# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='health.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0chealth.proto\"\x0f\n\rHealthRequest\"2\n\x0bHealthReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t20\n\x06Health\x12&\n\x06health\x12\x0e.HealthRequest\x1a\x0c.HealthReplyB)\n\'com.github.lburgazzoli.spring.boot.grpcb\x06proto3')
)




_HEALTHREQUEST = _descriptor.Descriptor(
  name='HealthRequest',
  full_name='HealthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=31,
)


_HEALTHREPLY = _descriptor.Descriptor(
  name='HealthReply',
  full_name='HealthReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='HealthReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='HealthReply.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['HealthRequest'] = _HEALTHREQUEST
DESCRIPTOR.message_types_by_name['HealthReply'] = _HEALTHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HealthRequest = _reflection.GeneratedProtocolMessageType('HealthRequest', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHREQUEST,
  __module__ = 'health_pb2'
  # @@protoc_insertion_point(class_scope:HealthRequest)
  ))
_sym_db.RegisterMessage(HealthRequest)

HealthReply = _reflection.GeneratedProtocolMessageType('HealthReply', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHREPLY,
  __module__ = 'health_pb2'
  # @@protoc_insertion_point(class_scope:HealthReply)
  ))
_sym_db.RegisterMessage(HealthReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\'com.github.lburgazzoli.spring.boot.grpc'))

_HEALTH = _descriptor.ServiceDescriptor(
  name='Health',
  full_name='Health',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=85,
  serialized_end=133,
  methods=[
  _descriptor.MethodDescriptor(
    name='health',
    full_name='Health.health',
    index=0,
    containing_service=None,
    input_type=_HEALTHREQUEST,
    output_type=_HEALTHREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEALTH)

DESCRIPTOR.services_by_name['Health'] = _HEALTH

# @@protoc_insertion_point(module_scope)
