# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import health_pb2 as health__pb2


class HealthStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.health = channel.unary_unary(
        '/Health/health',
        request_serializer=health__pb2.HealthRequest.SerializeToString,
        response_deserializer=health__pb2.HealthReply.FromString,
        )


class HealthServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def health(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HealthServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'health': grpc.unary_unary_rpc_method_handler(
          servicer.health,
          request_deserializer=health__pb2.HealthRequest.FromString,
          response_serializer=health__pb2.HealthReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Health', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
