# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import verifier_pb2 as verifier__pb2


class VerifierStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.verify = channel.unary_unary(
        '/Verifier/verify',
        request_serializer=verifier__pb2.VerifyRequest.SerializeToString,
        response_deserializer=verifier__pb2.VerifyReply.FromString,
        )


class VerifierServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def verify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VerifierServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'verify': grpc.unary_unary_rpc_method_handler(
          servicer.verify,
          request_deserializer=verifier__pb2.VerifyRequest.FromString,
          response_serializer=verifier__pb2.VerifyReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Verifier', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
