# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verifier.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='verifier.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0everifier.proto\"y\n\rVerifyRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12,\n\x07options\x18\x02 \x03(\x0b\x32\x1b.VerifyRequest.OptionsEntry\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1e\n\x0bVerifyReply\x12\x0f\n\x07message\x18\x01 \x01(\t22\n\x08Verifier\x12&\n\x06verify\x12\x0e.VerifyRequest\x1a\x0c.VerifyReplyB)\n\'com.github.lburgazzoli.spring.boot.grpcb\x06proto3')
)




_VERIFYREQUEST_OPTIONSENTRY = _descriptor.Descriptor(
  name='OptionsEntry',
  full_name='VerifyRequest.OptionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='VerifyRequest.OptionsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='VerifyRequest.OptionsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=139,
)

_VERIFYREQUEST = _descriptor.Descriptor(
  name='VerifyRequest',
  full_name='VerifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='VerifyRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='options', full_name='VerifyRequest.options', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_VERIFYREQUEST_OPTIONSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=139,
)


_VERIFYREPLY = _descriptor.Descriptor(
  name='VerifyReply',
  full_name='VerifyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='VerifyReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=171,
)

_VERIFYREQUEST_OPTIONSENTRY.containing_type = _VERIFYREQUEST
_VERIFYREQUEST.fields_by_name['options'].message_type = _VERIFYREQUEST_OPTIONSENTRY
DESCRIPTOR.message_types_by_name['VerifyRequest'] = _VERIFYREQUEST
DESCRIPTOR.message_types_by_name['VerifyReply'] = _VERIFYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VerifyRequest = _reflection.GeneratedProtocolMessageType('VerifyRequest', (_message.Message,), dict(

  OptionsEntry = _reflection.GeneratedProtocolMessageType('OptionsEntry', (_message.Message,), dict(
    DESCRIPTOR = _VERIFYREQUEST_OPTIONSENTRY,
    __module__ = 'verifier_pb2'
    # @@protoc_insertion_point(class_scope:VerifyRequest.OptionsEntry)
    ))
  ,
  DESCRIPTOR = _VERIFYREQUEST,
  __module__ = 'verifier_pb2'
  # @@protoc_insertion_point(class_scope:VerifyRequest)
  ))
_sym_db.RegisterMessage(VerifyRequest)
_sym_db.RegisterMessage(VerifyRequest.OptionsEntry)

VerifyReply = _reflection.GeneratedProtocolMessageType('VerifyReply', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYREPLY,
  __module__ = 'verifier_pb2'
  # @@protoc_insertion_point(class_scope:VerifyReply)
  ))
_sym_db.RegisterMessage(VerifyReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\'com.github.lburgazzoli.spring.boot.grpc'))
_VERIFYREQUEST_OPTIONSENTRY.has_options = True
_VERIFYREQUEST_OPTIONSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_VERIFIER = _descriptor.ServiceDescriptor(
  name='Verifier',
  full_name='Verifier',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=173,
  serialized_end=223,
  methods=[
  _descriptor.MethodDescriptor(
    name='verify',
    full_name='Verifier.verify',
    index=0,
    containing_service=None,
    input_type=_VERIFYREQUEST,
    output_type=_VERIFYREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VERIFIER)

DESCRIPTOR.services_by_name['Verifier'] = _VERIFIER

# @@protoc_insertion_point(module_scope)
